load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "longhorn_lib",
    srcs = [],
    visibility = ["//visibility:public"],
    target_compatible_with = [
        "@platforms//cpu:arm",
        "@platforms//os:none",
    ],
)
