"""OpenOCD for Flashing"""

filegroup(
    name = "openocd_flashing_script",
    srcs = ["flash.py"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "g4_flashing_cfg",
    srcs = ["stm32g4.cfg"],
    visibility = ["//visibility:public"],
)

exports_files(["flash.py"])